### ISSUE TITLE
YiedSAFE DOI leading nowhere?

### ISSUE THREAD

**Issue by palmajoao** [euraf/AF_FAIRness#28]
https://github.com/euraf/AF_FAIRness/blob/0c13db06d1fba1240f2d9dc012808665a2b7e6c9/catalogue/tools/yieldsafe_v2.json#L8

This DOI does not leat to the tool... Needs an update

**Comment by anaraqueltomas** [comment]
The Cranfield Repository had DOIs when this entry was added. Now they don't seem to have them anymore. Both YieldSAFE and FarmSAFE updated to the repo handler uri (commit https://github.com/euraf/AF_FAIRness/commit/e2a6d0f858244b3cce908d671a719e3a97e19485). (This makes me wonder how permanent are the permalinks like DOI)

**Comment by palmajoao** [comment]
this should be the link  to the model: https://dspace.lib.cranfield.ac.uk/handle/1826/22344
